management:
  endpoints:
    web:
      exposure:
        include: metrics,prometheus
  statsd:
    metrics:
      export:
        enabled: false
        # バッファリングせずに送信したい場合に指定
        #buffered: false
  otlp:
    metrics:
      export:
        enabled: false
logging:
  level:
    dev.irof.kanjava:
      UdpReceiver: debug
irof:
  udp-receiver:
    enabled: true
    port: 8125
server:
  tomcat:
    mbeanregistry:
      enabled: true